In [17]:
from pathlib import Path

import pandas as pd

In [18]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [19]:
cwd = Path.cwd()
FILE = 'fc_log.json'

In [20]:
df = pd.read_json(FILE)
df.sort_values(by='accuracy', ascending=False).head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum,best accuracy
13,2,9,0.382263,0.062451,Adam,NaN,1.195344,2.368466,64,0.750000,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,25.0,0.219515,NaN,NaN,NaN,NaN
12,2,9,0.382263,0.062451,Adam,NaN,1.195344,2.368466,64,0.750000,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,25.0,0.219515,NaN,NaN,NaN,NaN
15,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.729167,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,NaN
16,2,4,0.248242,0.004054,SGD,NaN,2.492983,2.299266,16,0.729167,fix alyer order and bias = False,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,72.0,0.407569,NaN,NaN,0.322146,NaN
14,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.729167,cpu,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df[::-1].head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum,best accuracy
18,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.708333,get best acc 100 trial,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,100,30,NaN,NaN,NaN,NaN,NaN,0.791667
17,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.708333,get best acc,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,0.791667
16,2,4,0.248242,0.004054,SGD,NaN,2.492983,2.299266,16,0.729167,fix alyer order and bias = False,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,72.0,0.407569,NaN,NaN,0.322146,NaN
15,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.729167,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,NaN
14,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.729167,cpu,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,NaN