In [6]:
from pathlib import Path
import pandas as pd

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
cwd = Path.cwd()

In [9]:
df = pd.read_json('fc_log.json')
df.sort_values(by='accuracy', ascending=False).head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum
7,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.723404,test seed function,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
6,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.723404,test seed function,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
5,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.723404,test for seed,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
4,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.723404,test run,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
11,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.708333,test new idx,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN

In [10]:
df[::-1].head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum
11,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.708333,test new idx,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
10,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.708333,test new idx,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN
9,1,42,0.357427,0.000534,SGD,NaN,1.732724,1.912140,16,0.666667,test new idx,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,0.289223
8,1,42,0.357427,0.000534,SGD,NaN,1.732724,1.912140,16,0.666667,test new inx,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,0.289223
7,1,44,0.418882,0.003550,Adam,NaN,2.426490,2.521570,32,0.723404,test seed function,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN