In [11]:
from pathlib import Path
import pandas as pd

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [13]:
cwd = Path.cwd()
FILE = 'conv.json'

In [14]:
df = pd.read_json(FILE)
df.sort_values(by='accuracy', ascending=False).head()

,n_conv,n_fc,n_channels_conv0,n_channels_conv1,n_channels_conv2,kernel_size_conv0,kernel_size_conv1,kernel_size_conv2,padding_conv0,padding_conv1,padding_conv2,dropout_conv0,dropout_conv1,dropout_conv2,n_units_fc0,n_units_fc1,n_units_fc2,dropout_fc0,dropout_fc1,dropout_fc2,lr,optimizer,w1,w2,batch_size,comment,bands,out_features,seed,epochs,image_size,num_trials,patience,accuracy,best accuracy
0,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,get baseline best acc,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.78125
1,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,test seed,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.78125

In [15]:
df[::-1].head()

,n_conv,n_fc,n_channels_conv0,n_channels_conv1,n_channels_conv2,kernel_size_conv0,kernel_size_conv1,kernel_size_conv2,padding_conv0,padding_conv1,padding_conv2,dropout_conv0,dropout_conv1,dropout_conv2,n_units_fc0,n_units_fc1,n_units_fc2,dropout_fc0,dropout_fc1,dropout_fc2,lr,optimizer,w1,w2,batch_size,comment,bands,out_features,seed,epochs,image_size,num_trials,patience,accuracy,best accuracy
1,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,test seed,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.78125
0,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,get baseline best acc,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.78125